name: Update README

on:
  schedule:
    - cron: "* */12 * * *"
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    name: Update Profile README
    permissions:
      contents: write

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4.2.2
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
      
      - name: GitHub - Activity - Readme
        uses: jamesgeorge007/github-activity-readme@v0.4.4
        with:
          # Your GitHub username
          GH_USERNAME: ${{ github.repository_owner }}
          # The maximum number of lines populated in your readme file
          MAX_LINES: 10
          # The file location to write changes to
          TARGET_FILE: README.md
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
